import { SCHEMA_VERSION } from '../shared/constants';
import type { NormalizedDesign, PageScan } from '../shared/types';
import { emptyCoverage } from '../shared/types';

export function sampleScan(): PageScan {
  return {
    schemaVersion: SCHEMA_VERSION,
    metadata: {
      url: 'https://fixture.example/page?token=REDACTED',
      urlRedacted: true,
      title: 'Page2Design fixture',
      language: 'en',
      direction: 'ltr',
      scannedAt: '2026-08-24T00:00:00.000Z',
      viewportWidth: 1280,
      viewportHeight: 720,
      devicePixelRatio: 1,
      scrollWidth: 1280,
      scrollHeight: 1600,
      documentBackground: 'rgb(246, 243, 238)',
      colorScheme: 'light',
      restoredScrollX: 0,
      restoredScrollY: 0,
      hostname: 'fixture.example',
    },
    page: {
      viewportWidth: 1280,
      viewportHeight: 720,
      documentWidth: 1280,
      documentHeight: 1600,
      devicePixelRatio: 1,
    },
    sections: [
      {
        id: 'sec_el_1',
        name: 'Main',
        nameInferred: false,
        rootElementId: 'el_1',
        bounds: { x: 0, y: 80, width: 880, height: 900 },
        background: 'rgba(0, 0, 0, 0)',
        containerWidth: 880,
        layoutMode: 'block',
        contentSummary: 'Measured design, not guessed style',
        assetIds: ['asset_1'],
        colorValues: ['#122033'],
        typographySignatures: ['aaaa'],
        confidence: 0.9,
        provenance: 'semantic',
      },
    ],
    elements: [
      {
        id: 'el_1',
        parentId: null,
        childIndex: 0,
        tagName: 'main',
        attributes: {},
        elementId: null,
        classNames: [],
        role: null,
        visibility: { visible: true },
        bounds: { x: 0, y: 80, width: 880, height: 900 },
        styleSignature: 'aaaa',
        directText: '',
        sectionId: 'sec_el_1',
        assetIds: [],
      },
    ],
    styleRegistry: {
      aaaa: { display: 'block', color: 'rgb(18, 32, 51)', 'font-size': '16px' },
    },
    assets: [
      {
        id: 'asset_1',
        type: 'image',
        sourceUrl: 'https://fixture.example/hero.png',
        resolvedUrl: 'https://fixture.example/hero.png',
        localPath: 'assets/images/asset_1.png',
        mimeType: 'image/png',
        intrinsicWidth: 640,
        intrinsicHeight: 400,
        renderedWidth: 420,
        renderedHeight: 262,
        elementIds: ['el_2'],
        sectionIds: ['sec_el_1'],
        downloadStatus: 'pending',
        failureReason: null,
        licenseReviewRequired: false,
        inlineSvg: null,
        alt: 'Blue hero graphic',
      },
    ],
    colors: [
      {
        original: ['#1d4ed8'],
        canonicalRgba: 'rgba(29, 78, 216, 1)',
        canonicalHex: '#1D4ED8',
        properties: ['background-color'],
        count: 4,
        elementIds: ['el_3'],
        source: 'background',
      },
    ],
    typography: [
      {
        signature: 'type1',
        fontFamily: 'Georgia, serif',
        fontSize: '42px',
        fontWeight: '700',
        fontStyle: 'normal',
        lineHeight: '48px',
        letterSpacing: 'normal',
        fontStretch: 'normal',
        textTransform: 'none',
        textDecoration: 'none',
        textAlign: 'start',
        fontFeatureSettings: 'normal',
        fontVariationSettings: 'normal',
        count: 1,
        elementIds: ['el_4'],
        selectors: ['h1'],
      },
    ],
    spacing: [{ value: '24px', px: 24, properties: ['padding'], count: 3, elementIds: ['el_1'] }],
    radii: [
      { value: '16px', px: 16, properties: ['border-radius'], count: 2, elementIds: ['el_5'] },
    ],
    shadows: [
      {
        value: '0 12px 30px rgba(18, 32, 51, 0.12)',
        count: 2,
        properties: ['box-shadow'],
        elementIds: ['el_5'],
      },
    ],
    cssVariables: [{ name: '--accent', value: '#1d4ed8', source: 'root', elementId: null }],
    interactions: [
      { elementId: 'el_6', kind: 'button', trigger: 'click / keyboard', notes: 'button' },
    ],
    content: [
      {
        id: 'c1',
        kind: 'heading',
        level: 1,
        text: 'Measured design, not guessed style',
        href: null,
        elementId: 'el_4',
        sectionId: 'sec_el_1',
        order: 0,
      },
    ],
    pseudos: [],
    mediaQueries: [
      { raw: '(max-width: 720px)', readable: true, notes: 'Read from stylesheet cssRules.' },
    ],
    limitations: [],
    coverage: emptyCoverage(),
    lazyLoad: { attempted: true, truncated: false, reason: null, finalScrollHeight: 1600 },
    viewportSnapshots: [],
  };
}

export function sampleDesign(): NormalizedDesign {
  const raw = sampleScan();
  return {
    schemaVersion: SCHEMA_VERSION,
    metadata: raw.metadata,
    sections: [
      {
        id: 'sec_el_1',
        name: 'Main',
        nameInferred: false,
        rootElementId: 'el_1',
        bounds: raw.sections[0]!.bounds,
        background: 'transparent',
        containerWidth: 880,
        layoutMode: 'block',
        contentSummary: 'Main',
        assetIds: ['asset_1'],
        colorTokenIds: ['color_1'],
        typographyTokenIds: ['type_1'],
        confidence: 0.9,
        provenance: 'semantic',
      },
    ],
    components: [
      {
        id: 'comp_button_1',
        kind: 'button',
        name: 'Button pattern 1',
        nameInferred: true,
        confidence: 0.7,
        elementIds: ['el_6'],
        notes: 'Observed 1 similar clickable control(s).',
      },
    ],
    tokens: {
      colors: [
        {
          id: 'color_1',
          name: 'background-1',
          nameInferred: true,
          hex: '#1D4ED8',
          rgba: 'rgba(29, 78, 216, 1)',
          hsl: 'hsl(224 76% 48%)',
          oklch: 'oklch(0.5 0.2 260)',
          original: ['#1d4ed8'],
          count: 4,
          properties: ['background-color'],
          elementIds: ['el_3'],
          role: 'background',
          roleInferred: true,
          nearDuplicates: [],
        },
      ],
      typography: [
        {
          id: 'type_1',
          name: 'heading-1',
          nameInferred: true,
          fontFamily: 'Georgia, serif',
          fontSize: '42px',
          fontWeight: '700',
          fontStyle: 'normal',
          lineHeight: '48px',
          letterSpacing: 'normal',
          textTransform: 'none',
          textDecoration: 'none',
          textAlign: 'start',
          count: 1,
          elementIds: ['el_4'],
          selectors: ['h1'],
          licenseReviewRequired: true,
        },
      ],
      spacing: [
        {
          id: 'space_1',
          name: 'space-1',
          nameInferred: true,
          value: '24px',
          px: 24,
          count: 3,
          properties: ['padding'],
        },
      ],
      radii: [
        {
          id: 'radius_1',
          name: 'radius-1',
          nameInferred: true,
          value: '16px',
          px: 16,
          count: 2,
          properties: ['border-radius'],
        },
      ],
      shadows: [
        {
          id: 'shadow_1',
          name: 'shadow-1',
          nameInferred: true,
          value: '0 12px 30px rgba(18, 32, 51, 0.12)',
          px: null,
          count: 2,
          properties: ['box-shadow'],
        },
      ],
    },
    assets: raw.assets,
    responsive: [
      {
        viewportWidth: 1280,
        viewportHeight: 720,
        captured: true,
        mediaQueries: raw.mediaQueries,
        notes: 'Measured from the active tab at scan time.',
      },
    ],
    content: raw.content,
    limitations: [
      {
        code: 'SINGLE_VIEWPORT',
        message: 'Only the current rendered viewport was scanned.',
        severity: 'info',
      },
    ],
    coverage: {
      relevantElements: 1,
      visibleTextBlocks: 1,
      discoveredAssets: 1,
      downloadedAssets: 0,
      typographyRecords: 1,
      styledElements: 1,
      associatedSections: 1,
      screenshotAvailable: false,
      notes: ['No screenshot is attached to this scan yet.'],
    },
    page: raw.page,
    styleRegistry: raw.styleRegistry,
  };
}
