export const SCHEMA_VERSION = '1.0.0'
export const MESSAGE_SCHEMA_VERSION = '1.0.0'
export const EXTENSION_NAME = 'Page2Design'
export const DB_NAME = 'page2design'
export const DB_VERSION = 1
export const STALE_SCAN_MS = 24 * 60 * 60 * 1000
export const INCOMPLETE_SCAN_MS = 60 * 60 * 1000
export const ELEMENT_CHUNK_SIZE = 40
export const ASSET_FETCH_CONCURRENCY = 4
export const MAX_ASSETS = 500
export const MAX_ASSET_BYTES = 8 * 1024 * 1024
export const MAX_TOTAL_ASSET_BYTES = 80 * 1024 * 1024
export const MAX_SCAN_HEIGHT = 20000
export const MAX_LAZY_LOAD_MS = 12000
export const MAX_ELEMENTS = 4000
export const MAX_SCREENSHOT_TILES = 12
export const DOM_SCAN_YIELD_EVERY = 80
export const MAX_PSEUDOS = 400
export const MAX_PSEUDO_STYLE_QUERIES = 800
export const STYLE_CHUNK_SIZE = 80
export const ASSET_CHUNK_SIZE = 25
export const CONTENT_CHUNK_SIZE = 80
export const TOKEN_CHUNK_SIZE = 100
export const MAX_STORED_SCANS = 8
export const OVERLAY_WIDTH = 336
export const OVERLAY_WIDE_WIDTH = 560
export const SENSITIVE_QUERY_KEYS = [
  'token',
  'access_token',
  'refresh_token',
  'id_token',
  'session',
  'sessionid',
  'auth',
  'authorization',
  'password',
  'passwd',
  'secret',
  'api_key',
  'apikey',
  'key',
  'code',
  'otp',
]

export const STYLE_ALLOWLIST = [
  'display',
  'position',
  'top',
  'right',
  'bottom',
  'left',
  'inset',
  'width',
  'height',
  'min-width',
  'min-height',
  'max-width',
  'max-height',
  'box-sizing',
  'margin',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
  'padding',
  'padding-top',
  'padding-right',
  'padding-bottom',
  'padding-left',
  'gap',
  'row-gap',
  'column-gap',
  'flex-direction',
  'flex-wrap',
  'flex',
  'flex-grow',
  'flex-shrink',
  'flex-basis',
  'justify-content',
  'align-items',
  'align-content',
  'align-self',
  'grid-template-columns',
  'grid-template-rows',
  'grid-auto-flow',
  'place-items',
  'background-color',
  'background-image',
  'background-size',
  'background-position',
  'background-repeat',
  'color',
  'border',
  'border-width',
  'border-style',
  'border-color',
  'border-radius',
  'border-top-left-radius',
  'border-top-right-radius',
  'border-bottom-right-radius',
  'border-bottom-left-radius',
  'outline',
  'box-shadow',
  'text-shadow',
  'opacity',
  'font-family',
  'font-size',
  'font-weight',
  'font-style',
  'font-stretch',
  'line-height',
  'letter-spacing',
  'text-transform',
  'text-decoration',
  'text-align',
  'font-feature-settings',
  'font-variation-settings',
  'white-space',
  'overflow',
  'overflow-x',
  'overflow-y',
  'transform',
  'z-index',
  'object-fit',
  'object-position',
  'transition-property',
  'transition-duration',
  'animation-name',
  'animation-duration',
  'cursor',
  'fill',
  'stroke',
] as const

export const SAFE_ATTRIBUTES = new Set([
  'id',
  'class',
  'role',
  'href',
  'src',
  'srcset',
  'sizes',
  'alt',
  'title',
  'rel',
  'target',
  'type',
  'for',
  'name',
  'placeholder',
  'aria-label',
  'aria-labelledby',
  'aria-describedby',
  'aria-hidden',
  'aria-expanded',
  'aria-current',
  'aria-controls',
  'loading',
  'decoding',
  'width',
  'height',
  'colspan',
  'rowspan',
  'scope',
  'open',
  'disabled',
  'readonly',
  'required',
  'multiple',
  'tabindex',
  'contenteditable',
  'draggable',
  'hidden',
  'lang',
  'dir',
  'poster',
  'preload',
  'controls',
  'autoplay',
  'loop',
  'muted',
  'playsinline',
  'crossorigin',
  'referrerpolicy',
  'fetchpriority',
  'decoding',
  'ismap',
  'usemap',
  'span',
  'start',
  'reversed',
  'cite',
  'datetime',
  'download',
  'hreflang',
  'media',
  'ping',
  'itemprop',
  'itemscope',
  'itemtype',
])

export const SENSITIVE_INPUT_TYPES = new Set([
  'password',
  'hidden',
  'email',
  'tel',
  'number',
  'credit-card',
  'cc-number',
  'cc-csc',
  'cc-exp',
  'cc-exp-month',
  'cc-exp-year',
  'cc-name',
])

export const SKIP_TAGS = new Set(['SCRIPT', 'STYLE', 'LINK', 'META', 'NOSCRIPT', 'TEMPLATE', 'HEAD'])
